# Configuration File for Aerial Self Host #
Email: "email@example.com"
Password: "Password!"
# Status (shown under name in friends list) #
# Leave blank for "Playing Fortnite" #
Status: ""
Accept Friend Requests: Yes
Accept Party Invites: No
# Platforms: WIN, PSN, XBL, NSW, AND, MAC, IOS #
Platform: "WIN"
# Cosmetics #
# All cosmetics *MUST* be IDs, not names! #
# Leave blank for none #
Cosmetics:
  Outfit: "CID_565_Athena_Commando_F_RockClimber"
  Back Bling: "BID_122_HalloweenTomato"
  Harvesting Tool: ""
  Banner:
    Design: "otherbanner31"
    Color: "defaultcolor3"
    Season Level: 1337
  Battle Pass:
    Has Purchased: No
    Level: 0
    XP Boost Self: 0
    XP Boost Others: 0
# Promote another party member whenever possible #
Yield Leadership: Yes
# Authorization Settings #
# Don't touch this unless you know what you're doing #
Authorization: {}
